project:
  type: book
  output-dir: docs

book:
  title: "LearningDiary"
  author: "Michael Hathorn"
  date: "2023/01/29"
  chapters:
    - index.qmd
    - intro.qmd
    - Week 1.qmd
    - week 2.qmd
    - week 3.qmd
    - week 4.qmd
    - week 5.qmd
    - week 6.qmd
    - week 7.qmd
    - week 8.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

